### ISSUE TITLE
GetPrefixItems

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#10]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L112
Тут (и видел ниже) для case insensitive сравнения используется ToLower \ ToUpper. Это плохой подход, потому что ToLower\ToUpper создает в памяти дополнительную строку. Для case insensetive сравнения\поиска есть специальные методы строк, использование их вместо ToLower\ToUpper позволяет снизить нагрузку на память и работают они быстрее. Надо исправить тут и ниже, где такой подход встречается.

**Comment by Iga27** [comment]
использовал перегрузку метода StartsWith() c параметром StringComparison.CurrentCultureIgnoreCase
вместо использования ToLower()
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L104

**Comment by Iga27** [comment]
использовал перегрузку метода StartsWith() c параметром StringComparison.CurrentCultureIgnoreCase
вместо использования ToLower()
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L104
