### ISSUE TITLE
PropagateItemsByPositionIndex<T>

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#11]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L145-L153
Вместо такого велосипеда можно использовать стандартный метод https://msdn.microsoft.com/en-us/library/bb348899(v=vs.110).aspx

**Comment by Iga27** [comment]
применил метод Enumerable.Repeat()
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L136
