### ISSUE TITLE
GetUsedChars

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#12]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L170-L171
Неудачный подход, входной параметр может последовательно читать строки из громадного файла. Метод string.Join сразу прочитает все данные (может несколько гигабайт) в память, памяти может не хватить. Надо учиться последовательно работать с небольшой текущей порцией информации, не считывая все данные в память. Для этого и придумали IEnumerable и yield return.

**Comment by Iga27** [comment]
вместо String.Join() использовал SelectMany() ,который будет последовательно обрабатывать входящую информацию
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L153
