### ISSUE TITLE
GetCountOfStrings

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#13]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L270-L272
Тут можно сдлеать без foreach (все задания в этом проекте не требуют foreach), только с использованием Linq-методов. И ниже тоже надо будет убрать foreach везде, где он встречается.

**Comment by Iga27** [comment]
убрал foreach. использовал вместо него LINQ-метод Select()
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L253
