### ISSUE TITLE
GetMissingDigits

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#14]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L422-L424
1) Тут опять string.Join, который все считывает в память.
2) string - это IEnumerable<char>, поэтому можно просто использовать `var array = "0123456789";`

**Comment by Iga27** [comment]
вместо String.Join использовал LINQ-метод SelectMany()
исправил определение  на  ` var array = "0123456789";`
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L377-L379
