### ISSUE TITLE
SortDigitNamesByNumericOrder

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#15]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L442
Почему используется тип new List<string>() ? Самый простой тип, который тут требуется - это массив, использование List - это overhead.

**Comment by Iga27** [comment]
вместо List использовал массив `var list=new string[]{"zero","one","two","three","four","five","six","seven","eight","nine"}`
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L397-L398
