### ISSUE TITLE
GetCommonChars

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#16]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L478-L488
Для того, чтобы вычислить data.Count() нужно пройти весь data от начала до конца один раз. Поэтому все остальные обращения могут теоритически уже не работать, так как один проход по IEnumerable уже закончился. Задача просто решается с помощью методов работы с множествами.

**Comment by Iga27** [comment]
убрал data.Count(). Cодержит ли последовательность элементы проверял с помощью `data.Any()` ,который не будет считывать всё в память
использовал метод работы с множествами Intersect()
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L433
