### ISSUE TITLE
GetSumOfAllInts

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#17]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L504
Любое приведение или проверка типов is/as - это плохой стиль. Есть два специальных метода, которые работают с типами в Enumerable, нужно выбрать подходящий.

**Comment by Iga27** [comment]
использовал метод OfType() 
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L449
