### ISSUE TITLE
GetStringsOnly

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#18]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L521
Тут опять, есть простой метод для достижения результата.

**Comment by Iga27** [comment]
использовал метод OfType() для выборки элементов заданного типа
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L466
