### ISSUE TITLE
IsAllStringsAreUppercase

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#19]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L572-L575
Тут опять после data.Count() данные один раз прочитались и больше не придут. И зачем нужен второй return?

**Comment by Iga27** [comment]
убрал data.Count(). Вместо этого использовал метод DefaultIfEmpty()  и  условие  `.All(x => !String.IsNullOrEmpty(x) `
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L517
