### ISSUE TITLE
ReadPlanetInfoFromXlsx

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#2]
Вот эти строки дублируются, copy-paste стиль: https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L35-L40

ElementAt(..) я рекомендую забыть, потому что для IEnumerable этот метод можно использовать только один раз (один проход) в общем случае:
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L59
Почему бы тут не использовать простой массив?

**Comment by Iga27** [comment]
Дублирующийся код вынес в private метод GetDocument()
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L45-L50
и убрал ElementAt
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L30-L43
