### ISSUE TITLE
GetNextVersionFromList

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#20]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L632
Думаю, что можно либо Take(1) либо FirstOrDefault(), одно из двух, два этих метода вместе должны возратить такой же результат, какой и любой один из них.

**Comment by Iga27** [comment]
убрал Take(1)
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L574
