### ISSUE TITLE
GetAverageOfDoubleValues

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#21]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L713-L719
Тут опять data.Count(), и вместо нескольких последовательных методов фильтрации по типу и аггрегации используются условия.

**Comment by Iga27** [comment]
Использовал фильтрацию по типу с помощью `OfType<Double>()` и метод аггрегации Average()
https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L650
