### ISSUE TITLE
CreateHierarchy

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#22]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/LinqToXml/LinqToXml/LinqToXml.cs#L22-L28
Тут странный подход, в прошлом задании нужно было научиться использовать method syntax, а тут неожиданно всплывает method syntax. А вообще это задание на использование https://msdn.microsoft.com/en-us/library/mt693049.aspx , которое позволяет достаточно наглядно формировать xml.

**Comment by Iga27** [comment]
применил method syntax
https://github.com/Iga27/tasks/blob/master/LinqToXml/LinqToXml/LinqToXml.cs#L20-L25
