### ISSUE TITLE
GetFlattenString

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#23]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/LinqToXml/LinqToXml/LinqToXml.cs#L141
RTFM https://msdn.microsoft.com/en-us/library/bb551415(v=vs.110).aspx

**Comment by Iga27** [comment]
применил метод ToString()
https://github.com/Iga27/tasks/blob/master/LinqToXml/LinqToXml/LinqToXml.cs#L138
