### ISSUE TITLE
GetOrdersValue

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#24]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/LinqToXml/LinqToXml/LinqToXml.cs#L151-L164
Тут задание на использование Join. Результат можно получить c помощью только Linq.

**Comment by Iga27** [comment]
убрал foreach. использовал Linq. Объединил две последовательности products и values методом Join() и получил сумму
https://github.com/Iga27/tasks/blob/master/LinqToXml/LinqToXml/LinqToXml.cs#L148-L155
