### ISSUE TITLE
ReadPlanetInfoFromXlsx

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#25]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/IOStreams/IOStreams/TestTasks.cs#L32-L53
Учились-учились Linq, а тут опять вложенные foreach съехали.

https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/IOStreams/IOStreams/TestTasks.cs#L59
Тут Stream открывается, а кто его закрывать будет?

**Comment by Iga27** [comment]
Использовал Linq,чтобы получить последовательности planets и radii.Затем объединил их с помощью метода Zip()
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L30-L43

Закрыл Stream с помощью using
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L47-L49
