### ISSUE TITLE
GetPublicObsoleteClasses

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#26]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Reflection/Reflection.Tasks/CommonTasks.cs#L20-L26
Опять foreach там, где можно простым linq все сделать.

**Comment by Iga27** [comment]
Сделал с помощью Linq 
https://github.com/Iga27/tasks/blob/master/Reflection/Reflection.Tasks/CommonTasks.cs#L22-L23
