### ISSUE TITLE
GetPropertyValue<T> / SetPropertyValue<T>

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#27]
Тут два очень похожих куска кода, которые делают почти одно и тоже:
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Reflection/Reflection.Tasks/CommonTasks.cs#L49-L53

https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Reflection/Reflection.Tasks/CommonTasks.cs#L77-L81

И опять вместо foreach можно сделать просто с помощью linq.

**Comment by Iga27** [comment]
Похожие части кода вынес в отдельный private метод GetSinglePropertyVal()
https://github.com/Iga27/tasks/blob/master/Reflection/Reflection.Tasks/CommonTasks.cs#L54-L58
