### ISSUE TITLE
GetUrlContent

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#28]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/AsyncIO/AsyncIO/Tasks.cs#L25-L29
Опять же все можно сделать в одну строку с помощью linq:
```
  return uris.Select(x=> new WebClient().DownloadString(x));
```

**Comment by Iga27** [comment]
поправил
https://github.com/Iga27/tasks/blob/master/AsyncIO/AsyncIO/Tasks.cs#L25
