### ISSUE TITLE
GetUrlContentAsync

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#29]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/AsyncIO/AsyncIO/Tasks.cs#L45-L56
Тут опять несколько проходов по uris.

Чтобы окончательно понять, зачем нужен IEnumerable и yield return, добавь тест, который начинает качать и на лету разархивировать файл со ссылками http://s3.amazonaws.com/alexa-static/top-1m.csv.zip и по одному отдавать ссылки через yield return в метод GetUrlContentAsync, который их сразу начнет качать.  Чтобы получилось так, что весь top-1m.csv.zip еще не выкачан, но первая ссылка уже скачана.
Я надеюсь, что это хоть немного поможет для понимания, как и зачем это все работает.

**Comment by Iga27** [comment]
Сделал с помощью Linq и убрал Count().
Сначала сгруппировал элементы по maxConcurrentStreams в каждой группе.
https://github.com/Iga27/tasks/blob/master/AsyncIO/AsyncIO/Tasks.cs#L41-L44
