### ISSUE TITLE
ReadEncodedText

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#3]
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L126-L131
Тут можно сделать одним методом. RTFM : https://msdn.microsoft.com/en-us/library/system.io.file(v=vs.110).aspx

**Comment by Iga27** [comment]
заменил на метод ReadAllText()
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L101
