### ISSUE TITLE
DecompressStream

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#4]
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L92-L113
Тут совсем необязятельно копировать все в промежуточный MemoryStream

**Comment by Iga27** [comment]
убрал промежуточный MemoryStream
https://github.com/Iga27/tasks/blob/master/IOStreams/IOStreams/TestTasks.cs#L78-L89
