### ISSUE TITLE
SortTupleArray<T1, T2, T3>

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#5]
https://github.com/Iga27/tasks/blob/master/Generics/Generics/Generics.cs#L113-L125
Copy-paste стиль. Чтобы добавить еще поле для сравнения, придется делать cope-paste.
Для того, чтобы избавиться от такого стиля, надо выносить неизменяемые части, а изменяемые заменять переменными.

**Comment by Iga27** [comment]
Убрал switch
Использовал массив Func для доступа к свойствам кортежа.
https://github.com/Iga27/tasks/blob/master/Generics/Generics/Generics.cs#L113-L114
