### ISSUE TITLE
CombinePredicates<T>

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#8]
https://github.com/Iga27/tasks/blob/master/Generics/Generics/Generics.cs#L219
`delegate (T x) { ... }` уже давно никто не пишет, можно же просто `x=>{...}`

И почему локальная переменная с большой буквы начинается?

**Comment by Iga27** [comment]
Исправил
https://github.com/Iga27/tasks/blob/master/Generics/Generics/Generics.cs#L203-L210
