### ISSUE TITLE
GetMovingSumSequence

### ISSUE THREAD

**Issue by aorgish** [Iga27/tasks#9]
https://github.com/Iga27/tasks/blob/f062ffcef5302cd96a8e8792bd0e57176f47b751/Enumerable/Enumerable/Task.cs#L81-L88
Тут используется несколько проходов по data, задача решается просто с ипользованием замыкания.

**Comment by Iga27** [comment]
исправил так: 
 https://github.com/Iga27/tasks/blob/master/Enumerable/Enumerable/Task.cs#L80
